apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: echo-team
  namespace: echo-team
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 80
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
