apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-app-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rafay-presales/demo-apps.git
    targetRevision: main
    path: echo/manifest/
  destination: 
    server: https://kubernetes.default.svc
    namespace: echo-team-stage
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
