apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 
    targetRevision: main
    path: helm-chart
  destination: 
    server: https://kubernetes.default.svc
    namespace: 
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
